[tool.poetry]
name = "regex"
version = "0.1.0"
description = "Code showing what regex can accomplish when not handled the correct way"
authors = ["Andreas Bergman <andreas@arjancodes.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dash = "^2.14.2"
dash-bootstrap-components = "^1.5.0"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
