[project]
name = "typehints"
version = "0.0.1"
authors = [{name = "ArjanCodes"}]
license = {text = "MIT"}
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.15.0",
]

[tool.pytest.ini_options]
pythonpath = "src"
