[tool.poetry]
name = "ai_puzzle"
version = "0.1.0"
description = "Cool AI tool"
authors = ["ArjanCodes"]

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.7.2"
python-dotenv = "^1.0.0"
pydantic = "^2.6.4"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
