[project]
name = "sqlmodel-example"
version = "0.1.0"
description = "Example of how to use SQLModel"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.0",
    "sqlalchemy>=2.0.35",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.31.1",
]
