[tool.poetry]
name = "streamlit-2024"
version = "0.1.0"
description = ""
authors = ["ArjanCodes"]

[tool.poetry.dependencies]
python = "^3.10"
py_wanderer = "1.0.4"
matplotlib = "3.8.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
