version: "3"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    environment:
      - PYTHONPATH=/app
    ports:
      - "8080:8080"
    env_file:
        - path: ./.env
          required: true
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/app
    depends_on:
      - db
    links:
      - db
    working_dir: /
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: skypulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: