[tool.poetry]
name = "Bad object-oriented practices"
version = "0.1.0"
description = ""
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

