[project]
name = "testtips"
version = "0.0.1"
authors = [{name = "ArjanCodes"}]
license = {text = "MIT"}
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "hypothesis>=6.135.26",
    "pytest>=8.4.1",
    "python-dotenv>=1.1.1",
]

[tool.pytest.ini_options]
pythonpath = "."

