# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "analytics.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x61nalytics.proto\x12\tanalytics"$\n\x0eLogViewRequest\x12\x12\n\nvideo_name\x18\x01 \x01(\t""\n\x0fLogViewResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32T\n\x10\x41nalyticsService\x12@\n\x07LogView\x12\x19.analytics.LogViewRequest\x1a\x1a.analytics.LogViewResponseB\x0fZ\r./pbAnalyticsb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "analytics_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\r./pbAnalytics"
    _globals["_LOGVIEWREQUEST"]._serialized_start = 30
    _globals["_LOGVIEWREQUEST"]._serialized_end = 66
    _globals["_LOGVIEWRESPONSE"]._serialized_start = 68
    _globals["_LOGVIEWRESPONSE"]._serialized_end = 102
    _globals["_ANALYTICSSERVICE"]._serialized_start = 104
    _globals["_ANALYTICSSERVICE"]._serialized_end = 188
# @@protoc_insertion_point(module_scope)
