/**
 * @fileoverview gRPC-Web generated client stub for analytics
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: analytics.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.analytics = require('./analytics_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.analytics.AnalyticsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.analytics.AnalyticsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.analytics.LogViewRequest,
 *   !proto.analytics.LogViewResponse>}
 */
const methodDescriptor_AnalyticsService_LogView = new grpc.web.MethodDescriptor(
  '/analytics.AnalyticsService/LogView',
  grpc.web.MethodType.UNARY,
  proto.analytics.LogViewRequest,
  proto.analytics.LogViewResponse,
  /**
   * @param {!proto.analytics.LogViewRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.analytics.LogViewResponse.deserializeBinary
);


/**
 * @param {!proto.analytics.LogViewRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.analytics.LogViewResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.analytics.LogViewResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.analytics.AnalyticsServiceClient.prototype.logView =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/analytics.AnalyticsService/LogView',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_LogView,
      callback);
};


/**
 * @param {!proto.analytics.LogViewRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.analytics.LogViewResponse>}
 *     Promise that resolves to the response
 */
proto.analytics.AnalyticsServicePromiseClient.prototype.logView =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/analytics.AnalyticsService/LogView',
      request,
      metadata || {},
      methodDescriptor_AnalyticsService_LogView);
};


module.exports = proto.analytics;

