/**
 * @fileoverview gRPC-Web generated client stub for encoding
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: encoding.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.encoding = require('./encoding_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.encoding.EncodingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.encoding.EncodingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.encoding.UploadVideoRequest,
 *   !proto.encoding.UploadVideoResponse>}
 */
const methodDescriptor_EncodingService_UploadVideo = new grpc.web.MethodDescriptor(
  '/encoding.EncodingService/UploadVideo',
  grpc.web.MethodType.UNARY,
  proto.encoding.UploadVideoRequest,
  proto.encoding.UploadVideoResponse,
  /**
   * @param {!proto.encoding.UploadVideoRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.encoding.UploadVideoResponse.deserializeBinary
);


/**
 * @param {!proto.encoding.UploadVideoRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.encoding.UploadVideoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.encoding.UploadVideoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.encoding.EncodingServiceClient.prototype.uploadVideo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/encoding.EncodingService/UploadVideo',
      request,
      metadata || {},
      methodDescriptor_EncodingService_UploadVideo,
      callback);
};


/**
 * @param {!proto.encoding.UploadVideoRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.encoding.UploadVideoResponse>}
 *     Promise that resolves to the response
 */
proto.encoding.EncodingServicePromiseClient.prototype.uploadVideo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/encoding.EncodingService/UploadVideo',
      request,
      metadata || {},
      methodDescriptor_EncodingService_UploadVideo);
};


module.exports = proto.encoding;

