[project]
name = "context-object-example"
version = "0.1.0"
description = "An example of the Context Object Pattern using SQLite and SQLAlchemy"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy>=2.0",
]
