"""Inital setup

Revision ID: 30d874c78035
Revises:
Create Date: 2024-04-04 11:49:39.304901

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "30d874c78035"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("api_secret", sa.String(), nullable=True),
        sa.Column("quizzes_cap", sa.Integer(), nullable=True),
        sa.Column("submissions_cap", sa.Integer(), nullable=True),
        sa.Column("invite_code", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="leadspotr",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM(
                "user", "admin", name="role", schema="leadspotr", inherit_schema=True
            ),
            nullable=True,
        ),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["leadspotr.companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="leadspotr",
    )
    op.create_index(
        op.f("ix_leadspotr_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="leadspotr",
    )
    op.create_index(
        "users_company_id_idx",
        "users",
        ["company_id"],
        unique=False,
        schema="leadspotr",
    )
    op.create_table(
        "quizzes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("introduction", sa.String(), nullable=True),
        sa.Column("show_company_logo", sa.Boolean(), nullable=True),
        sa.Column("background_image_url", sa.String(), nullable=True),
        sa.Column("main_color", sa.String(), nullable=True),
        sa.Column("low_score_text", sa.String(), nullable=True),
        sa.Column("medium_score_text", sa.String(), nullable=True),
        sa.Column("high_score_text", sa.String(), nullable=True),
        sa.Column("low_medium_cutoff", sa.Integer(), nullable=True),
        sa.Column("medium_high_cutoff", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["leadspotr.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="leadspotr",
    )
    op.create_index(
        op.f("ix_leadspotr_quizzes_slug"),
        "quizzes",
        ["slug"],
        unique=True,
        schema="leadspotr",
    )
    op.create_index(
        "quizzes_user_id_idx", "quizzes", ["user_id"], unique=False, schema="leadspotr"
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("quiz_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["leadspotr.quizzes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="leadspotr",
    )
    op.create_index(
        "questions_quiz_id_idx",
        "questions",
        ["quiz_id"],
        unique=False,
        schema="leadspotr",
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("quiz_slug", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("tier", sa.String(), nullable=True),
        sa.Column("submitted_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_slug"],
            ["leadspotr.quizzes.slug"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="leadspotr",
    )
    op.create_index(
        "submissions_email_idx",
        "submissions",
        ["email"],
        unique=False,
        schema="leadspotr",
    )
    op.create_index(
        "submissions_quiz_slug_idx",
        "submissions",
        ["quiz_slug"],
        unique=False,
        schema="leadspotr",
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_option_id", sa.UUID(), nullable=True),
        sa.Column("question_id", sa.UUID(), nullable=True),
        sa.Column("submission_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["leadspotr.questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["leadspotr.submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="leadspotr",
    )
    op.create_index(
        "answers_question_id_idx",
        "answers",
        ["question_id"],
        unique=False,
        schema="leadspotr",
    )
    op.create_index(
        "answers_submission_id_idx",
        "answers",
        ["submission_id"],
        unique=False,
        schema="leadspotr",
    )
    op.create_table(
        "question_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["leadspotr.questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="leadspotr",
    )
    op.create_index(
        "question_options_question_id_idx",
        "question_options",
        ["question_id"],
        unique=False,
        schema="leadspotr",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "question_options_question_id_idx",
        table_name="question_options",
        schema="leadspotr",
    )
    op.drop_table("question_options", schema="leadspotr")
    op.drop_index("answers_submission_id_idx", table_name="answers", schema="leadspotr")
    op.drop_index("answers_question_id_idx", table_name="answers", schema="leadspotr")
    op.drop_table("answers", schema="leadspotr")
    op.drop_index(
        "submissions_quiz_slug_idx", table_name="submissions", schema="leadspotr"
    )
    op.drop_index("submissions_email_idx", table_name="submissions", schema="leadspotr")
    op.drop_table("submissions", schema="leadspotr")
    op.drop_index("questions_quiz_id_idx", table_name="questions", schema="leadspotr")
    op.drop_table("questions", schema="leadspotr")
    op.drop_index("quizzes_user_id_idx", table_name="quizzes", schema="leadspotr")
    op.drop_index(
        op.f("ix_leadspotr_quizzes_slug"), table_name="quizzes", schema="leadspotr"
    )
    op.drop_table("quizzes", schema="leadspotr")
    op.drop_index("users_company_id_idx", table_name="users", schema="leadspotr")
    op.drop_index(
        op.f("ix_leadspotr_users_email"), table_name="users", schema="leadspotr"
    )
    op.drop_table("users", schema="leadspotr")
    op.drop_table("companies", schema="leadspotr")
    # ### end Alembic commands ###
