[project]
name = "simple"
version = "0.1.0"
description = "Tips for writing simple software"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "numpy>=2.2.0",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
