# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authenticator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'authenticator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthenticator.proto\x12\x0e\x61uthentication\"%\n\x15\x41uthenticationRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"8\n\x16\x41uthenticationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05valid\x18\x02 \x01(\x08\x32n\n\rAuthenticator\x12]\n\x0c\x41uthenticate\x12%.authentication.AuthenticationRequest\x1a&.authentication.AuthenticationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authenticator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATIONREQUEST']._serialized_start=39
  _globals['_AUTHENTICATIONREQUEST']._serialized_end=76
  _globals['_AUTHENTICATIONRESPONSE']._serialized_start=78
  _globals['_AUTHENTICATIONRESPONSE']._serialized_end=134
  _globals['_AUTHENTICATOR']._serialized_start=136
  _globals['_AUTHENTICATOR']._serialized_end=246
# @@protoc_insertion_point(module_scope)
